In [2]:
import numpy as np

In [22]:
a = np.array([[1, 2, 3, 4, 5],
                [6, 0, 1, 10, 1]])

b = np.array([1, 4])

In [23]:
corr = np.corrcoef(a, b, rowvar=False)

print(corr.shape)
print(corr)
print('------------------')
print(np.abs(corr[0, :]))

(6, 6)
[[ 1. -1. -1.  1. -1.  1.]
 [-1.  1.  1. -1.  1. -1.]
 [-1.  1.  1. -1.  1. -1.]
 [ 1. -1. -1.  1. -1.  1.]
 [-1.  1.  1. -1.  1. -1.]
 [ 1. -1. -1.  1. -1.  1.]]
------------------
[1. 1. 1. 1. 1. 1.]


In [24]:
i = 4

a = a[a[:, i] <= 4]
print(a)

[[ 6  0  1 10  1]]


In [117]:
root = np.array([1, 1, 1, 1, 1])
print(root.shape)
left = np.array([1, 2, 3, 4, 5])
right = np.array([6, 7, 8, 9, 10])
#test = 

joined = np.vstack((root, left, right))
print(joined.shape)
print("---------------------------")
joined2 = np.vstack((joined, root))
print(joined2)

(5,)
(3, 5)
---------------------------
[[ 1  1  1  1  1]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]]


In [66]:
root_T = np.array([[1], [2], [3]])
print(root_T.T.shape)
print(np.median(root_T.T))

(1, 3)
2.0


In [69]:
import pandas as pd
data = pd.read_csv('Data/Istanbul.csv')
data = data.values[:, 1:-1].astype('float64')
print(data.shape)

(536, 8)


In [51]:
inf = open("/Users/nickdinapoli/Documents/Georgia_Tech/CS_7646/ML4T_2022Spr/assess_learners/Data/Istanbul.csv")
print(inf)
#for s in inf.readlines()[1:]:
    #print(s)
    
print(inf.readlines()[1])
data = np.array([list(map(float, s.strip().split(","))) for s in inf.readlines()[1:]])
#data = data[:, 1:]
print(data)

<_io.TextIOWrapper name='/Users/nickdinapoli/Documents/Georgia_Tech/CS_7646/ML4T_2022Spr/assess_learners/Data/Istanbul.csv' mode='r' encoding='UTF-8'>
5-Jan-09,0.035753708,0.038376187,-0.004679315,0.002193419,0.003894376,0,0.031190229,0.012698039,0.028524462

[]


In [77]:
# print(data)
i = 0
print(np.median(data[:, i]))
SplitVal = 0.002188758

lefttree = data[data[:, i] <= SplitVal]

print(lefttree)
print(data.shape[0],lefttree.shape[0])

0.002188758
[[-0.02886173 -0.02635297 -0.03046913 ...  0.01729293 -0.03589858
  -0.0170728 ]
 [-0.06220808 -0.0847159   0.00339136 ... -0.04006131  0.02828315
  -0.00556096]
 [-0.02919103 -0.04236115 -0.02282263 ... -0.04903853 -0.05384947
  -0.01245126]
 ...
 [ 0.00019097 -0.0016526   0.00192291 ...  0.00056828  0.00562792
   0.00057157]
 [-0.01306904 -0.01370599 -0.02074215 ...  0.00135758 -0.01194168
  -0.01261533]
 [-0.00724632 -0.01944185  0.         ... -0.01791963 -0.01225155
  -0.00546489]]
536 268


In [101]:
inds_L = np.where(data[:, i] <= SplitVal)[0]
inds_R = np.where(data[:, i] > SplitVal)[0]
#print(inds_L[0])
print(inds_L.shape, inds_R.shape)
print(inds_L, inds_R)

(268,) (268,)
[  2   3   5   7   8  10  11  12  13  16  18  19  20  23  26  27  28  30
  31  32  34  36  38  39  40  43  45  47  50  51  52  58  60  64  65  66
  70  71  74  75  79  80  86  87  88  90  95  98 100 101 103 104 105 107
 112 113 114 117 118 125 126 127 129 130 131 133 136 138 148 149 150 152
 153 156 157 158 164 167 169 171 173 174 177 178 184 187 188 189 192 196
 198 199 203 205 206 207 208 210 212 213 217 218 220 221 222 223 225 226
 231 232 233 235 239 243 246 248 254 255 256 258 259 263 264 266 267 269
 271 272 273 274 275 277 279 283 285 286 287 288 293 296 297 298 299 300
 303 304 309 310 311 312 316 318 320 321 323 324 325 327 328 330 331 334
 335 336 337 338 340 342 343 346 347 349 353 354 357 358 359 365 369 370
 371 372 374 375 376 378 380 382 385 386 387 389 392 395 397 399 400 401
 404 405 407 410 411 412 414 415 421 422 423 424 429 431 433 434 437 439
 443 448 451 452 455 456 457 459 460 462 465 466 467 469 470 472 473 474
 478 481 482 483 485 486 487 488 489 

In [121]:
data_y = np.array([[1], [1], [1]])
print(data_y)
print(np.all(data_y == data_y[0]))

[[1]
 [1]
 [1]]
True


In [125]:
len(data.shape)

2

In [130]:
test = np.array([])
print(test.shape)

(0,)


In [133]:
print(data.shape[0])
n = data.shape[0]

536


In [136]:
#print(np.random.randint(n, size=n))
inds = np.random.randint(n, size=n)
#print(data[inds].shape)

(536, 8)


In [139]:
corr = corr = np.abs(np.corrcoef(data[:,:-1], data[:, -1], rowvar=False)[-1, :-1])

print(corr)

i = np.argmax(corr)
print(i)

[0.65551897 0.69076122 0.68754981 0.93639305 0.94896336 0.28375011
 0.62170413]
4


In [142]:
import math
math.sqrt()

ValueError: math domain error