In [44]:
import numpy as np

In [40]:
n, p = 1, .5  # number of trials, probability of each trial
test = np.random.binomial(n, p)
print(test)

0


In [41]:
if test:
    print('yes')

In [58]:
print(np.random.randint(0, 5, size=20))

[3 2 3 3 1 1 3 3 0 2 4 1 0 0 1 3 0 0 0 4]


In [75]:
test = np.zeros((1,4))
test = np.append(test, [[1, 2, 3,4]], axis=0)
print(test)

[[0. 0. 0. 0.]
 [1. 2. 3. 4.]]


In [73]:
print(test[1,1])

2.0


In [77]:
A = np.array([0, 1, 2, 3])
a, b, c, d = A.ravel()
print(b)

1
